services:
  the-guardian-api:
    build:
      context: .
      target: build
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - redis
    command: npm run dev
    environment:
      - APP_PORT=3000
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - THE_GUARDIAN_SECTION_ENDPOINT=https://content.guardianapis.com
      - THE_GUARDIAN_API_KEY=${THE_GUARDIAN_API_KEY}
      - CACHE_TTL=600
      - DEBUG_MODE=${DEBUG_MODE}
    
  redis:
    image: redis:7.4.0-alpine
    ports:
      - 6379:6379
